version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: taskflow_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root100
      MYSQL_DATABASE: taskflow
      MYSQL_USER: taskflow_user
      MYSQL_PASSWORD: ig2wCArpwP4PfFq
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: